blog1/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog1/', include('blog1.urls', namespace='blog1')),
]

blog1/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Comment(models.Model):
    pub_time = models.DateTimeField('评论发表时间', auto_now=True)
    content = models.TextField('评论内容', null=False, default='no comment')
    name = models.CharField('评论者名字', max_length=10, null=False)
    url = models.URLField(max_length=20, null=False)
    email = models.EmailField('评论者邮箱', max_length=20, null=False)
    article = models.ForeignKey('Article', verbose_name='评论所属文章', on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:20]


class Article(models.Model):
    title = models.CharField(max_length=70, null=False)
    content = models.TextField()
    create_time = models.DateTimeField()
    modifies_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

blog1/views.py
from django.shortcuts import render
from . import models
import datetime
# Create your views here.


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog1/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog1/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog1/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog1/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article_id = request.POST.get('article_id', '0')
    if str(article_id) == '0':
        if title == '':
            articles = models.Article.objects.all()
            return render(request, 'blog1/index.html', {'articles': articles})
        else:
            models.Article.objects.create(title=title, content=content)
            articles = models.Article.objects.all()
            return render(request, 'blog1/index.html', {'articles': articles})
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.body = content
        article.create_time = datetime.date
        article.save()
        return render(request, 'blog1/article_page.html', {'article': article})

blog1/templates/blog1/article_page.html
{% extends 'blog1/base.html' %}
{% block title %}article page{% endblock %}
{% block h1 %}<a href="{% url 'blog1:index' %}">回到主页</a>{% endblock %}
{% block main %}

    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ article.title }}</h1>
            <div class="entry-meta">
                <span class="post-author"><a href="#">Tlion</a></span>

                <span class="post-category">
                <a href="{% url 'blog1:edit_page' article.id %}">修改文章</a></span>

                <span class="comments-link"><a href="#">4 Comments</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ article.content }}
        </div>
    </article>
    <section class="comment-area">
        <h2>留下你的评论</h2>
        <form action="#" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <input type="text" name="name" placeholder="名字" required>
                </div>
                <div class="col-md-4">
                    <input type="email" name="email" placeholder="邮箱" required>
                </div>
                <div class="col-md-4">
                    <input type="text" name="url" placeholder="网址" required>
                </div>
                <input hidden name = "id" value="{{ article.id }}">
                <div class="col-md-12">
                    <textarea name="comment" rows="7" placeholder="" required></textarea>
                    <button class="" name="submit"><span>发表</span></button>
                </div>
            </div>    <!-- row -->
        </form>

        <div class="comment-list">
            <h2>评论列表</h2>
            <ul class="list-unstyled">
                <li class="comment-item">
                    <span class="name">追梦人物</span><time class="date">2017年3月12日 14:56</time>
                    <div class="text">
                        还不错哦
                    </div>
                </li>
                <li class="comment-item">
                    <span class="name">追梦人物</span><time class="date">2017年3月12日 14:56</time>
                    <div class="text">
                        还不错哦
                    </div>
                </li>
            </ul>
        </div>
    </section>
{% endblock %}

blog1/templates/blog1/base.html
<!DOCTYPE html PUBLIC>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}

	    <!-- css -->
        <link rel="stylesheet" href="{% static 'blog1/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'blog1/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'blog1/css/custom.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

        <!-- js -->
        <script src="{% static 'blog1/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog1/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog1/js/pace.min.js' %}"></script>
        <script src="{% static 'blog1/js/modernizr.custom.js' %}"></script>
        <script src="{% static 'blog1/js/script.js' %}"></script>
	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
                            <h1>{% block h1 %}{% endblock %}</h1>
                        </div>
					</div>
                    <!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href=" " data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href=" " data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href=" " data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href=" " data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.tlion.com/" >tlion</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
						{% block main %}{% endblock %}
					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">
							<h3 class="widget-title">Recent Posts</h3>
							<ul>
								<li>
									<a href="#">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</li>
								<li>
									<a href="#">Web Design is 95% Typography</a>
								</li>
								<li>
									<a href="#">Paper by FiftyThree</a>
								</li>
							</ul>
						</div>
						<div class="widget widget-archives">
							<h3 class="widget-title">Archives</h3>
							<ul>
								<li>
									<a href="#">4  <-->  2016</a>
								</li>
							</ul>
						</div>

						<div class="widget widget-category">
							<h3 class="widget-title">Category</h3>
							<ul>
								<li>
									<a href="#">Web Design</a>
								</li>
								<li>
									<a href="#">Web Development</a>
								</li>
								<li>
									<a href="#">SEO</a>
								</li>
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>

		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2016 tlion.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href=" ">Home</a></li>
					<li><a href=" ">Blog</a></li>
					<li><a href=" ">About</a></li>
					<li><a href=" ">Contact</a></li>
				</ul>
			</nav>
		</div>
		<script src="{% static 'blog1/js/script.js' %}"></script>
	</body>
</html>

blog1/templates/blog1/edit_page.html
{% extends 'blog1/base.html' %}
{% block title %}edit-page{% endblock %}
{% block h1 %}<a href="{% url 'blog1:index' %}">回到主页</a>{% endblock %}
{% block main %}
    <form action="{% url 'blog1:edit_action' %}" method="post" class="comment-form">
    {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">
        <div class="col-lg-12">
            <label>文章标题：
                <input type="text" name="title" value="{{ article.title }}">
            </label>
        </div>
        <br>
        <div class="col-md-12">
            <label>文章内容：<br>
                <textarea name="content" cols="100" rows="20">{{ article.content }}</textarea>
            </label><br>
                <button name="submit" class="button"><span>提交</span></button>
        </div>
    </form>
{% endblock %}

blog1/templates/blog1/index.html
{% extends 'blog1/base.html' %}
{% block title %}My &amp; blog{% endblock %}
{% block h1 %}<a href = '{% url 'blog1:edit_page' 0 %}'>new article</a>{% endblock %}
{% block main %}
    {% for article in articles %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href = "{% url 'blog1:article_page' article.id %}">{{ article.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">Web Design</a></span>

                    <span class="post-date"><a href="#"><time class="entry-date" datetime=" ">April 13, 2016</time></a></span>

                    <span class="post-author"><a href="#">Tlion-self</a></span>

                    <span class="comments-link"><a href="#">no Comment yet</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>nothing now!!!</p>
                <div class="read-more cl-effect-14">
                    <a href = "{% url 'blog1:article_page' article.id %}">Continue readinG <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% endfor %}
{% endblock %}

blog1/templates/blog1/pagination.html
<div id="pagenavi" class="noselect">
    {% if article_list.has_previous %} # 判断是否还有上一页，有的话要显示一个上一页按钮
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    # 页码号为1永远显示
    {% if first_page == current_page %} # 当前页就是第一页
        <span class="first-page current">1</span>
    {% else %} # 否则的话，第一页是可以点击的，点击后通过?page=1的形式把页码号传递给视图函数
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %} # 2以前的页码号要被显示成省略号了
        <span>...</span>
    {% endif %}

    {% for page in pages %} # 通过for循环把pages中的值显示出来
        {% if page == current_page %} # 是否当前页，按钮会显示不同的样式
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

      # pages最后一个值+1的值小于最大页码号，说明有页码号需要被省略号替换
    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

      # 永远显示最后一页的页码号，如果只有一页则前面已经显示了1就不用再显示了
    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    # 还有下一页，则显示一个下一页按钮
    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>